### ISSUE TITLE
Bilibili comics tachiyomi extension 

### ISSUE THREAD

**Issue by Vijaytechni** [alessandrojean/alessandrojean#1]
Bilibili comics extension chapters are not showing but i when go to the webview all the chapters are there but it's not loading or showing in the tachiyomi app Please fix this bug I been using bilibili Comics extension for months & it never happened but suddenly already uploaded chapters are not showing in the tachiyomi the Manhua i read is free & it's new chapters updated daily uploaded and all the new & free chapters are already available in the webview but it's 
Showing in the tachiyomi app i even try other app's aniyomi but it's has same issue please fix the bug

**Comment by alessandrojean** [comment]
You need to open the issue in the official extensions repository, not in a contributor fork...

**Comment by alessandrojean** [comment]
Also this is not even the right repository to you open an issue, it's not related at all, wtf man.

**Comment by arkon** [comment]
Pls fix

**Comment by alessandrojean** [comment]
They're not free, try to read and you will see you need to pay or wait a certain period of time to read. The extension **does not show any paid chapters on purpose** since we don't do any payment bypassing and will never do. Please stop insisting and again, **this is NOT the right repository to you open issues related to Tachiyomi extensions**.
